spring:
  application:
    name: springboot04_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: "0420"
